import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'title': 'EchoThread',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email Address',
      'password': 'Password',
      'phone': 'Phone Number',
      'name': 'Name',
      'role': 'Role',
      'dashboard': 'Dashboard',
      'profile': 'My Profile',
      'settings': 'Settings',
      'help': 'Help & Support',
      'about': 'About EchoThread',
      'logout': 'Logout',
      'welcome': 'Welcome Back',
      'theme_mode': 'Theme Mode',
      'selected_theme': 'Selected Theme',
      'language_selection': 'Language Selection',
      'selected_language': 'Selected Language',
      'donations': 'Donations',
      'volunteers': 'Volunteers',
      'users': 'Users',
      'status': 'Status',
      'active': 'Active',
      'inactive': 'Inactive',
      'accept_task': 'Accept Task',
      'mark_pickup': 'Mark Pickup Completed',
      'mark_delivered': 'Mark Delivered',
      'category': 'Category',
      'quantity': 'Quantity',
      'pickup_address': 'Pickup Address',
      'date': 'Date',
      'actions': 'Actions',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'already_have_account': 'Already have an account?',
      'enter_details': 'Enter your credentials to continue',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'about_mission': 'Our Mission',
      'about_project': 'Our Project',
      'about_dev': 'Developer Information',
      'about_contact': 'Contact Information',
      'home': 'Home',
      'total_donors': 'Total Donors',
      'total_ngos': 'Total NGOs',
      'pending_pickups': 'Pending Pickups',
      'completed_donations': 'Completed Donations',
      'reports': 'Reports',
      'notifications': 'Notifications',
      'completed_tasks': 'Completed Tasks',
      'donation_id': 'Donation ID',
      'ngo': 'NGO',
      'completion_date': 'Completion Date',
      'donor_name': 'Donor Name',
      'contact_details': 'Contact Details',
      'active_actions': 'Active Actions',
      'history': 'History',
      'accept': 'Accept',
      'reject': 'Reject',
      'assign_volunteer': 'Assign Volunteer',
      'distribute_to_needy': 'Distribute to Needy',
      'delete_record': 'Delete Record',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'save': 'Save',
      'update': 'Update',
      'close': 'Close',
      'validation_error': 'Validation Error',
      'all_fields_required': 'All fields are required.',
      'password_updated': 'Password updated successfully!',
      'config_saved': 'API Configuration Saved Successfully!',
      'welcome_back': 'Welcome Back!',
      'otp_sent': 'Verification code sent to your email!',
      'theme_customizations': 'Theme Customizations',
      'change_password': 'Change Password',
      'edit_profile': 'Edit Profile Credentials',
      'change_account_password': 'Change Account Password',
      'notification_settings': 'Notification Settings',
      'email_alerts': 'Email Alerts',
      'sms_alerts': 'SMS Alerts',
      'privacy_policy': 'Privacy Policies & Terms',
      'developer_sandbox': 'Developer Sandbox Configurations',
      'logout_confirm': 'Are you sure you want to log out?',
      'delete_confirm': 'Are you sure you want to delete this record?',
    },
    'kn': {
      'title': 'ಎಕೋಥ್ರೆಡ್',
      'login': 'ಲಾಗಿನ್',
      'register': 'ನೋಂದಣಿ',
      'email': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'password': 'ಗುಪ್ತಪದ',
      'phone': 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
      'name': 'ಹೆಸರು',
      'role': 'ಪಾತ್ರ',
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'settings': 'ಸಂಯೋಜನೆಗಳು',
      'help': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
      'about': 'ಎಕೋಥ್ರೆಡ್ ಬಗ್ಗೆ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'welcome': 'ಸ್ವಾಗತ',
      'theme_mode': 'ಥೀಮ್ ಮೋಡ್',
      'selected_theme': 'ಆಯ್ಕೆಮಾಡಿದ ಥೀಮ್',
      'language_selection': 'ಭಾಷೆ ಆಯ್ಕೆ',
      'selected_language': 'ಆಯ್ಕೆಮಾಡಿದ ಭಾಷೆ',
      'donations': 'ದೇಣಿಗೆಗಳು',
      'volunteers': 'ಸ್ವಯಂಸೇವಕರು',
      'users': 'ಬಳಕೆದಾರರು',
      'status': 'ಸ್ಥಿತಿ',
      'active': 'ಸಕ್ರಿಯ',
      'inactive': 'ನಿಷ್ಕ್ರಿಯ',
      'accept_task': 'ಕಾರ್ಯ ಸ್ವೀಕರಿಸಿ',
      'mark_pickup': 'ಪಿಕಪ್ ಪೂರ್ಣಗೊಂಡಿದೆ ಎಂದು ಗುರುತಿಸಿ',
      'mark_delivered': 'ತಲುಪಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
      'category': 'ವರ್ಗ',
      'quantity': 'ಪ್ರಮಾಣ',
      'pickup_address': 'ಪಿಕಪ್ ವಿಳಾಸ',
      'date': 'ದಿನಾಂಕ',
      'actions': 'ಕ್ರಮಗಳು',
      'forgot_password': 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
      'dont_have_account': 'ಖಾತೆ ಹೊಂದಿಲ್ಲವೇ?',
      'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?',
      'enter_details': 'ಮುಂದುವರೆಯಲು ನಿಮ್ಮ ರುಜುವಾತುಗಳನ್ನು ನಮೂದಿಸಿ',
      'sign_in': 'ಸೈನ್ ಇನ್',
      'sign_up': 'ಸೈನ್ ಅಪ್',
      'about_mission': 'ನಮ್ಮ ಧ್ಯೇಯ',
      'about_project': 'ನಮ್ಮ ಯೋಜನೆ',
      'about_dev': 'ಡೆವಲಪರ್ ಮಾಹಿತಿ',
      'about_contact': 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
      'home': 'ಮುಖಪುಟ',
      'total_donors': 'ಒಟ್ಟು ದಾನಿಗಳು',
      'total_ngos': 'ಒಟ್ಟು ಎನ್‌ಜಿಒಗಳು',
      'pending_pickups': 'ಬಾಕಿ ಉಳಿದಿರುವ ಪಿಕಪ್‌ಗಳು',
      'completed_donations': 'ಪೂರ್ಣಗೊಂಡ ದೇಣಿಗೆಗಳು',
      'reports': 'ವರದಿಗಳು',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'completed_tasks': 'ಪೂರ್ಣಗೊಂಡ ಕಾರ್ಯಗಳು',
      'donation_id': 'ದೇಣಿಗೆ ಐಡಿ',
      'ngo': 'ಎನ್‌ಜಿಒ',
      'completion_date': 'ಪೂರ್ಣಗೊಂಡ ದಿನಾಂಕ',
      'donor_name': 'ದಾನಿ ಹೆಸರು',
      'contact_details': 'ಸಂಪರ್ಕ ವಿವರಗಳು',
      'active_actions': 'ಸಕ್ರಿಯ ಕ್ರಮಗಳು',
      'history': 'ಇತಿಹಾಸ',
      'accept': 'ಸ್ವೀಕರಿಸಿ',
      'reject': 'ತಿರಸ್ಕರಿಸಿ',
      'assign_volunteer': 'ಸ್ವಯಂಸೇವಕರನ್ನು ನಿಯೋಜಿಸಿ',
      'distribute_to_needy': 'ಬಡವರಿಗೆ ಹಂಚಿ',
      'delete_record': 'ದಾಖಲೆ ಅಳಿಸು',
      'delete': 'ಅಳಿಸು',
      'cancel': 'ರದ್ದುಗೊಳಿಸು',
      'save': 'ಉಳಿಸು',
      'update': 'ನವೀಕರಿಸಿ',
      'close': 'ಮುಚ್ಚು',
      'validation_error': 'ಮೌಲ್ಯೀಕರಣ ದೋಷ',
      'all_fields_required': 'ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳು ಕಡ್ಡಾಯವಾಗಿವೆ.',
      'password_updated': 'ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
      'config_saved': 'API ಕಾನ್ಫಿಗರೇಶನ್ ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!',
      'welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ!',
      'otp_sent': 'ಪರಿಶೀಲನಾ ಕೋಡ್ ಅನ್ನು ನಿಮ್ಮ ಇಮೇಲ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ!',
      'theme_customizations': 'ಥೀಮ್ ಗ್ರಾಹಕೀಕರಣಗಳು',
      'change_password': 'ಪಾಸ್ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ರುಜುವಾತುಗಳನ್ನು ಸಂಪಾದಿಸಿ',
      'change_account_password': 'ಖಾತೆ ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
      'notification_settings': 'ಅಧಿಸೂಚನೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'email_alerts': 'ಇಮೇಲ್ ಎಚ್ಚರಿಕೆಗಳು',
      'sms_alerts': 'ಎಸ್‌ಎಂಎಸ್ ಎಚ್ಚರಿಕೆಗಳು',
      'privacy_policy': 'ಗೌಪ್ಯತೆ ನೀತಿಗಳು ಮತ್ತು ನಿಯಮಗಳು',
      'developer_sandbox': 'ಡೆವಲಪರ್ ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್ ಕಾನ್ಫಿಗರೇಶನ್‌ಗಳು',
      'logout_confirm': 'ನೀವು ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?',
      'delete_confirm': 'ಈ ದಾಖಲೆಯನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?',
    },
    'hi': {
      'title': 'इकोथ्रेड',
      'login': 'लॉगिन',
      'register': 'पंजीकरण',
      'email': 'ईमेल पता',
      'password': 'पासवर्ड',
      'phone': 'फ़ोन नंबर',
      'name': 'नाम',
      'role': 'भूमिका',
      'dashboard': 'डैशबोर्ड',
      'profile': 'मेरी प्रोफाइल',
      'settings': 'सेटिंग्स',
      'help': 'सहायता और सहायता',
      'about': 'इकोथ्रेड के बारे में',
      'logout': 'लॉग आउट',
      'welcome': 'स्वागत हे',
      'theme_mode': 'थीम मोड',
      'selected_theme': 'चयनित थीम',
      'language_selection': 'भाषा चयन',
      'selected_language': 'चयनित भाषा',
      'donations': 'दान',
      'volunteers': 'स्वयंसेवक',
      'users': 'उपयोगकर्ता',
      'status': 'स्थिति',
      'active': 'सक्रिय',
      'inactive': 'निष्क्रिय',
      'accept_task': 'कार्य स्वीकार करें',
      'mark_pickup': 'पिकअप पूर्ण चिह्नित करें',
      'mark_delivered': 'वितरित चिह्नित करें',
      'category': 'श्रेणी',
      'quantity': 'मात्रा',
      'pickup_address': 'पिकअप पता',
      'date': 'दिनांक',
      'actions': 'कार्रवाई',
      'forgot_password': 'पासवर्ड भूल गए?',
      'dont_have_account': 'खाता नहीं है?',
      'already_have_account': 'पहले से ही एक खाता है?',
      'enter_details': 'जारी रखने के लिए अपने क्रेडेंशियल दर्ज करें',
      'sign_in': 'साइन इन',
      'sign_up': 'साइन अप',
      'about_mission': 'हमारा लक्ष्य',
      'about_project': 'हमारी परियोजना',
      'about_dev': 'डेवलपर की जानकारी',
      'about_contact': 'संपर्क जानकारी',
      'home': 'मुख्य पृष्ठ',
      'total_donors': 'कुल दाता',
      'total_ngos': 'कुल एनजीओ',
      'pending_pickups': 'लंबित पिकअप',
      'completed_donations': 'पूरे किए गए दान',
      'reports': 'रिपोर्ट',
      'notifications': 'सूचनाएं',
      'completed_tasks': 'पूरे किए गए कार्य',
      'donation_id': 'दान आईडी',
      'ngo': 'एनजीओ',
      'completion_date': 'समाप्ति तिथि',
      'donor_name': 'दाता का नाम',
      'contact_details': 'संपर्क विवरण',
      'active_actions': 'सक्रिय कार्रवाई',
      'history': 'इतिहास',
      'accept': 'स्वीकार करें',
      'reject': 'अस्वीकार करें',
      'assign_volunteer': 'स्वयंसेवक सौंपें',
      'distribute_to_needy': 'जरूरतमंदों को वितरित करें',
      'delete_record': 'रिकॉर्ड हटाएं',
      'delete': 'हटाएं',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'update': 'अपडेट करें',
      'close': 'बंद करें',
      'validation_error': 'सत्यापन त्रुटि',
      'all_fields_required': 'सभी क्षेत्र आवश्यक हैं।',
      'password_updated': 'पासवर्ड सफलतापूर्वक अपडेट किया गया!',
      'config_saved': 'एपीआई कॉन्फ़िगरेशन सफलतापूर्वक सहेजा गया!',
      'welcome_back': 'वापसी पर स्वागत है!',
      'otp_sent': 'सत्यापन कोड आपके ईमेल पर भेजा गया है!',
      'theme_customizations': 'थीम कस्टमाइज़ेशन',
      'change_password': 'पासवर्ड बदलें',
      'edit_profile': 'प्रोफ़ाइल क्रेडेंशियल संपादित करें',
      'change_account_password': 'खाता पासवर्ड बदलें',
      'notification_settings': 'अधिसूचना सेटिंग्स',
      'email_alerts': 'ईमेल अलर्ट',
      'sms_alerts': 'एसएमएस अलर्ट',
      'privacy_policy': 'गोपनीयता नीतियां और शर्तें',
      'developer_sandbox': 'डेवलपर सैंडबॉक्स कॉन्फ़िगरेशन',
      'logout_confirm': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
      'delete_confirm': 'क्या आप वाकई इस रिकॉर्ड को हटाना चाहते हैं?',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'kn', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(LocalizationsDelegate<AppLocalizations> old) => false;
}

extension LocalizationExtension on BuildContext {
  String translate(String key) => AppLocalizations.of(this)?.translate(key) ?? key;
}
