// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDakIL6sdUOIfQrGuJZWAqsNHKD33adWsU',
    appId: '1:504964174749:web:d8b23c7f4ec68a50c81574',
    messagingSenderId: '504964174749',
    projectId: 'echothread-6729a',
    authDomain: 'echothread-6729a.firebaseapp.com',
    storageBucket: 'echothread-6729a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT38WqWxrnyboiFEU94-aEGw_fLlVdTkI',
    appId: '1:504964174749:android:b57d887f19af4165c81574',
    messagingSenderId: '504964174749',
    projectId: 'echothread-6729a',
    storageBucket: 'echothread-6729a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQp0HyYLa1uU0u07fs_zxUmpsetdUbt6M',
    appId: '1:504964174749:ios:d82c5608eff8ff26c81574',
    messagingSenderId: '504964174749',
    projectId: 'echothread-6729a',
    storageBucket: 'echothread-6729a.firebasestorage.app',
    iosBundleId: 'com.example.echoThread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQp0HyYLa1uU0u07fs_zxUmpsetdUbt6M',
    appId: '1:504964174749:ios:d82c5608eff8ff26c81574',
    messagingSenderId: '504964174749',
    projectId: 'echothread-6729a',
    storageBucket: 'echothread-6729a.firebasestorage.app',
    iosBundleId: 'com.example.echoThread',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDakIL6sdUOIfQrGuJZWAqsNHKD33adWsU',
    appId: '1:504964174749:web:e18698f51e2388aac81574',
    messagingSenderId: '504964174749',
    projectId: 'echothread-6729a',
    authDomain: 'echothread-6729a.firebaseapp.com',
    storageBucket: 'echothread-6729a.firebasestorage.app',
  );
}
